admins: []
forwards:
- source: -1001526895831
  dest:
  - -1001545223265
  offset: 379368
  end: 0
- source: https://t.me/HazUploads
  dest:
  - -1001757358469
  offset: 28574
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 1.0
plugins: {}
