version: 2.1

# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
